/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpMean */

#ifndef _Included_DpMean
#define _Included_DpMean
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DpMean
 * Method:    createAlgorithm
 * Signature: (ZZDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_DpMean_createAlgorithm
  (JNIEnv *, jobject, jboolean, jboolean, jdouble, jdouble, jdouble);

/*
 * Class:     DpMean
 * Method:    insertElement
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_DpMean_insertElement
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     DpMean
 * Method:    getAlgorithmResult
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_DpMean_getAlgorithmResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
