/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExampleJava */

#ifndef _Included_ExampleJava
#define _Included_ExampleJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExampleJava
 * Method:    Sum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_Sum
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    Mean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ExampleJava_Mean
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    CountAbove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_CountAbove
  (JNIEnv *, jobject, jint);

/*
 * Class:     ExampleJava
 * Method:    Max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_Max
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    PrivacyBudget
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ExampleJava_PrivacyBudget
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    PrivateSum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_PrivateSum
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    PrivateMean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ExampleJava_PrivateMean
  (JNIEnv *, jobject);

/*
 * Class:     ExampleJava
 * Method:    PrivateCountAbove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_PrivateCountAbove
  (JNIEnv *, jobject, jint);

/*
 * Class:     ExampleJava
 * Method:    PrivateMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ExampleJava_PrivateMax
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
