/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    Sum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_Sum
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    Mean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Main_Mean
  (JNIEnv *, jobject);

  /*
   * Class:     Main
   * Method:    DefaultEpsilon
   * Signature: ()D
   */
  JNIEXPORT jdouble JNICALL Java_Main_DefaultEpsilon
    (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    CountAbove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_CountAbove
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    Max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_Max
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    PrivacyBudget
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Main_PrivacyBudget
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    PrivateSum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_PrivateSum
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    PrivateMean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Main_PrivateMean
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    PrivateCountAbove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_PrivateCountAbove
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    PrivateMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_PrivateMax
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
