/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Dp_func */

#ifndef _Included_Dp_func
#define _Included_Dp_func
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dp_func
 * Method:    DpCount
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpCount___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Dp_func
 * Method:    DpCount
 * Signature: ([DD)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpCount___3DD
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpSum___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([ID)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpSum___3ID
  (JNIEnv *, jobject, jintArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([IDDD)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpSum___3IDDD
  (JNIEnv *, jobject, jintArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([IDD)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpSum___3IDD
  (JNIEnv *, jobject, jintArray, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpSum___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([DD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpSum___3DD
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpSum___3DDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpSum
 * Signature: ([DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpSum___3DDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpMean
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpMean___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Dp_func
 * Method:    DpMean
 * Signature: ([DD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpMean___3DD
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpMean
 * Signature: ([DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpMean___3DDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpMean
 * Signature: ([DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpMean___3DDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpVariance
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpVariance___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Dp_func
 * Method:    DpVariance
 * Signature: ([DD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpVariance___3DD
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpVariance
 * Signature: ([DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpVariance___3DDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpVariance
 * Signature: ([DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpVariance___3DDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpStd
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpStd___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Dp_func
 * Method:    DpStd
 * Signature: ([DD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpStd___3DD
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpStd
 * Signature: ([DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpStd___3DDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpStd
 * Signature: ([DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpStd___3DDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpNtile
 * Signature: ([IDDD)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpNtile___3IDDD
  (JNIEnv *, jobject, jintArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpNtile
 * Signature: ([IDDDD)I
 */
JNIEXPORT jint JNICALL Java_Dp_1func_DpNtile___3IDDDD
  (JNIEnv *, jobject, jintArray, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpNtile
 * Signature: ([DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpNtile___3DDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    DpNtile
 * Signature: ([DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_Dp_1func_DpNtile___3DDDDD
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Dp_func
 * Method:    setEpsilon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Dp_1func_setEpsilon
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
