/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpFunc */

#ifndef _Included_DpFunc
#define _Included_DpFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DpFunc
 * Method:    DpCount
 * Signature: ([DZD)I
 */
JNIEXPORT jint JNICALL Java_DpFunc_DpCount
  (JNIEnv *, jobject, jdoubleArray, jboolean, jdouble);

/*
 * Class:     DpFunc
 * Method:    DpSum
 * Signature: ([DZZDDD)D
 */
JNIEXPORT jdouble JNICALL Java_DpFunc_DpSum
  (JNIEnv *, jobject, jdoubleArray, jboolean, jboolean, jdouble, jdouble, jdouble);

/*
 * Class:     DpFunc
 * Method:    DpMean
 * Signature: ([DZZDDD)D
 */
JNIEXPORT jdouble JNICALL Java_DpFunc_DpMean
  (JNIEnv *, jobject, jdoubleArray, jboolean, jboolean, jdouble, jdouble, jdouble);

/*
 * Class:     DpFunc
 * Method:    DpVariance
 * Signature: ([DZZDDD)D
 */
JNIEXPORT jdouble JNICALL Java_DpFunc_DpVariance
  (JNIEnv *, jobject, jdoubleArray, jboolean, jboolean, jdouble, jdouble, jdouble);

/*
 * Class:     DpFunc
 * Method:    DpStd
 * Signature: ([DZZDDD)D
 */
JNIEXPORT jdouble JNICALL Java_DpFunc_DpStd
  (JNIEnv *, jobject, jdoubleArray, jboolean, jboolean, jdouble, jdouble, jdouble);

/*
 * Class:     DpFunc
 * Method:    DpNtile
 * Signature: ([DDDDZD)D
 */
JNIEXPORT jdouble JNICALL Java_DpFunc_DpNtile
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble, jboolean, jdouble);

#ifdef __cplusplus
}
#endif
#endif
